### ISSUE TITLE
Provided by whom?

### ISSUE THREAD

**Issue by jljenneman** [sixtriangles/sixtriangles.github.io#7]
![66121D49-EB17-4CD5-B6A4-AF381D43E9B6](https://user-images.githubusercontent.com/60621503/86692742-ab390e00-bfcf-11ea-985e-600d344e4fd6.png)

Need based scholarships provided by the school and private charities, individuals, businesses, etc? Yes. Provided by the government? No.

**Comment by sixtriangles** [comment]
Need based scholarships in general. If you believe that they are important, from anyone, then you agree with the statement.
I believe that this question falls under the Equality of Opportunity/Outcome/Burden triangle, specifically under the Opportunity segment. By checking strongly agree, you will increase your equality of opportunity portion, otherwise you will decrease it. Does equality of opportunity imply equality of opportunity provided by government, or equality of opportunity provided by the school, private charities, etc?  Not really. If someone with full minarchy has a high opportunity equality score, you can probably assume that that means opportunity provided by private institutions.
